package org.example.enums;

public enum ERole {
    ROLE_MODERATOR,
    ROLE_WRITER,
    REGIONAL_HEAD,
    REGIONAL_TEAM_HEAD,
    HEADQUARTER_CURATOR,
    DISTRICT_CURATOR,
    UNIVERSITY_COMMUNITY_CENTER_CURATOR,
    SCHOOL_SQUAD_CURATOR,
    TEAM_LEADER
}
